name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      PYTHONUTF8: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
        shell: pwsh

      - name: Build executable (PyInstaller)
        run: pyinstaller --noconfirm --clean --onefile --name PineoMonitor main.py

      - name: Package ZIP
        run: |
          powershell Compress-Archive -Path dist\PineoMonitor.exe -DestinationPath PineoMonitor_win_x64.zip -Force

      - name: Generate checksum
        run: |
          certutil -hashfile PineoMonitor_win_x64.zip SHA256 > SHA256.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PineoMonitor_win_x64.zip
            SHA256.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
